### ISSUE TITLE
New version update request: Protobuf 3.0.0 is officially released

### ISSUE THREAD

**Issue by pgrosu** [googlegenomics/utils-java#110]
So Proto3 is officially out now!

https://github.com/google/protobuf/releases/tag/v3.0.0

Can we bump it to `3.0.0`, as well as `protobuf-maven-plugin`, which is now at `0.6.5` in [these lines](https://github.com/googlegenomics/utils-java/blob/master/pom.xml#L292-L300):

```
<artifactId>protobuf-maven-plugin</artifactId>
<version>0.5.0</version>
...
<protocArtifact>com.google.protobuf:protoc:3.0.0-beta-2:exe:${os.detected.classifier}</protocArtifact>
```

Thanks,
Paul

**Comment by deflaux** [comment]
Completed via https://github.com/googlegenomics/utils-java/pull/120
