### ISSUE TITLE
Throughput and Timing of the API

### ISSUE THREAD

**Issue by pgrosu** [googlegenomics/utils-java#12]
Based on some analysis of the API throughput below is a summary of the conversation from #9, and the latest test using `v1beta2` which measures the same throughput as v1beta - this could slow things down when trying to analyze whole genomes but I am sure we can come up with a solution:

```
$ curl -X POST -H "Content-Type: application/json" -d '{"variantSetIds":["3049512673186936334"], "referenceName":"chr2","start":1,"end":85000,"pageToken":null}' https://www.googleapis.com/genomics/v1beta/variants/search?oauth_token=ya29.... > one_page_token.txt

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.9M    0 12.9M  100   104  2288k     17  0:00:06  0:00:05  0:00:01 3658k

$ curl -X POST -H "Content-Type: application/json" -d '{"variantSetIds":["3049512673186936334"], "referenceName":"chr2","start":1,"end":85000,"pageToken":null}' https://www.googleapis.com/genomics/v1beta2/variants/search?oauth_token=ya29.... > one_page_token.txt

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.9M    0 12.9M  100   104  1769k     13  0:00:08  0:00:07  0:00:01 3975k
$
```

It might be helpful to try out a few different approaches to optimize it for large data throughput.  In order to not post the whole discussion again and to catch people up on the analysis so far, below is our discussion in chronological order:

@dionloy : https://github.com/googlegenomics/utils-java/issues/9#issuecomment-60462202

@pgrosu : https://github.com/googlegenomics/utils-java/issues/9#issuecomment-60470893

@siddharthab : https://github.com/googlegenomics/utils-java/issues/9#issuecomment-60471658

@pgrosu : https://github.com/googlegenomics/utils-java/issues/9#issuecomment-60473101

@dionloy : https://github.com/googlegenomics/utils-java/issues/9#issuecomment-60488629

@siddharthab : https://github.com/googlegenomics/utils-java/issues/9#issuecomment-60488905

@dionloy : https://github.com/googlegenomics/utils-java/issues/9#issuecomment-60489275

@elmer-garduno : https://github.com/googlegenomics/utils-java/issues/9#issuecomment-60502091

@siddharthab : https://github.com/googlegenomics/utils-java/issues/9#issuecomment-60502713

@pgrosu : https://github.com/googlegenomics/utils-java/issues/9#issuecomment-60502722

@pgrosu : https://github.com/googlegenomics/utils-java/issues/9#issuecomment-60502759

I'm sure we can come up with a solution.

~p

**Comment by deflaux** [comment]
Closing this issue in favor of the new GRPC support for Reads and Variants.
