### ISSUE TITLE
Null pointer exception for variant start field

### ISSUE THREAD

**Issue by deflaux** [googlegenomics/utils-java#24]
The NPE is here https://github.com/googlegenomics/utils-java/blob/master/src/main/java/com/google/cloud/genomics/utils/Paginator.java#L863

Due to some recent server-side changes, if integer fields such as `start` are zero the field will not be present in the json --> therefore null.

Here's some data with `start` not specified
```
java -jar target/genomics-tools-client-java-v1beta2.jar searchvariants \
    --variant_set_id 3049512673186936334 \
    --start 0 --end 2 --reference_name chr17 --pretty_print
Getting variants from: Platinum Genomes
{
  "calls" : [ {
    "callSetId" : "3049512673186936334-4",
    "callSetName" : "NA12887",
    "genotype" : [ 0, 0 ],
    "info" : {
      "DP" : [ "23" ],
      "GQX" : [ "63" ],
      "MQ" : [ "29" ],
      "FILTER" : [ "PASS" ]
    }
  }, {
    "callSetId" : "3049512673186936334-6",
    "callSetName" : "NA12888",
    "genotype" : [ 0, 0 ],
    "info" : {
      "DP" : [ "21" ],
      "GQX" : [ "63" ],
      "MQ" : [ "32" ],
      "FILTER" : [ "PASS" ]
    }
  } ],
  "created" : "1415846479246",
  "end" : "18",
  "filter" : [ "PASS" ],
  "id" : "CI7s77ro84KpKhIFY2hyMTcg-Ziqt6rb3ZID",
  "info" : {
    "BLOCKAVG_min30p3a" : [ "" ]
  },
  "referenceBases" : "A",
  "referenceName" : "chr17",
  "variantSetId" : "3049512673186936334"
}
{
  "calls" : [ {
    "callSetId" : "3049512673186936334-3",
    "callSetName" : "NA12889",
    "genotype" : [ 0, 0 ],
    "info" : {
      "DP" : [ "26" ],
      "GQX" : [ "75" ],
      "MQ" : [ "30" ],
      "FILTER" : [ "PASS" ]
    }
  }, {
    "callSetId" : "3049512673186936334-9",
    "callSetName" : "NA12891",
    "genotype" : [ 0, 0 ],
    "info" : {
      "DP" : [ "20" ],
      "GQX" : [ "60" ],
      "MQ" : [ "29" ],
      "FILTER" : [ "PASS" ]
    }
  } ],
  "created" : "1415846479246",
  "end" : "22",
  "filter" : [ "PASS" ],
  "id" : "CI7s77ro84KpKhIFY2hyMTcgp7qF18CSje4l",
  "info" : {
    "BLOCKAVG_min30p3a" : [ "" ]
  },
  "referenceBases" : "A",
  "referenceName" : "chr17",
  "variantSetId" : "3049512673186936334"
}
```

**Comment by pgrosu** [comment]
I'm confused, but in this instance `start` looks to be specified.  So what this supposed to be an example where `start` is not specified?  I thought `start` always has to be specified.  It would be good to also provide release notes on the server-side changes to help out user interaction via the client.

**Comment by deflaux** [comment]
This was fixed server-side. The json now contains `"start" : null` which downstream is returned as zero by variant.getStart().

@pgrosu "start" was missing from the JSON response listed in this issue.  Agreed on the release notes.

**Comment by pgrosu** [comment]
I see, thanks Nicole - I thought you meant when setting the parameters.  But a small question, what does `start` being set to `null` mean for a Variant?  Why not just set it to 0, which I think is what you're interpreting it as.  If others create their own clients/tools, they would not know that `null` means 0.  When I look at [the Variants link](https://cloud.google.com/genomics/v1beta2/reference/variants) under the documentation regarding `start`, it does not mention `null`:

```
start 	long 	The position at which this variant occurs (0-based). This corresponds to the first base of the string of reference bases.
```

So seeing the following might confuse them:
```
  "referenceBases" : "A",
  "referenceName" : "chr17",
  "start" : null,
  "variantSetId" : "3049512673186936334"
}
```

Thank you for looking into the possibility for release notes.

~p

**Comment by dionloy** [comment]
Hi Paul,

This is a side effect of some common infrastructure pieces that we're using
at Google. We're looking into seeing if we can change that.

**Comment by pgrosu** [comment]
Thanks Dion for the clarification,
Paul
